"""Add offer field to Meal

Revision ID: 010e4feb9dfd
Revises: 
Create Date: 2024-04-02 01:04:24.259059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010e4feb9dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer', sa.Boolean(), nullable=False, server_default=sa.text('False')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('offer')

    # ### end Alembic commands ###
